remove garbage. improve code.

diff --git a/src/tick b/src/tick
--- a/src/tick
+++ b/src/tick
@@ -4,26 +4,34 @@ OUTFILE="$HOME/.tick/protocol.csv"
 OUTDIR="${OUTFILE%/*}"
 PARSER="$HOME/bin/particl"
 
+# check outdir existence
+# create if none
 [[ ! -d $OUTDIR ]] && {
 	mkdir -vp "$OUTDIR" || exit -1
 }
 
+# check outfile existence
+# create if none
 [[ ! -f $OUTFILE ]] && {
 	touch $OUTFILE || exit -1
 }
 
 shopt -s extglob
 
+# give a short usage
 short_help () {
-	echo "usage: ${0##*/} -hadmyDY [command] <time> <description>"
+	echo "usage: ${0##*/} -hadmyDY [command] [comment]"
 }
 
+# give a detailed help
 help() {
 	short_help
 
 	cat <<-EOF
 
+		========
 		options:
+		========
 
 		-h	help
 		
@@ -38,29 +46,38 @@ help() {
 		-a	set amamedis
 
 
+		=========
 		commands:
+		=========
 
-		<HH[:MM]>			duration
-		<HH:MM>-<HH:MM>		from-to	
-		parse
+		<HH[:MM]>         duration
+		<HH:MM>-<HH:MM>   from-to	
+
+		parse             parse protocol
 		state
 		report
-		sync
+		sync              sync protocol to backup location
 
-		undo
-		redo
+		undo              undo last entry
+		redo              redo last undo
 
-		completion
+		completion        install shell completion
 
 EOF
 }
+
+# append entry to $OUTFILE
+entry() {
+	echo $date $(bc <<< "scale=2; $durations/3600")h \($durations\) $from-$to \($unix_from-$unix_to\) $comment 
+	echo $identifier,$(date -d "$date" +%Y,%m,%d),$durations,$unix_from,$unix_to,\"$comment\" >> $OUTFILE
+}
+
+# command line parsing
 
 # if an option or bunch of options
 # they are parsed into an array
 # if option demands an argument 
 # its read from $1 and $skip_next is increased
-# shifts are done for option, bunch of options
-# and parameter demanded by an option
 
 # the stripped commandline
 # we will append to this so
@@ -71,17 +88,17 @@ stripped=""
 # number of arguments to be skipped
 skip_next=0
 
+# set identifier to Euratel
+identifier=e
+
 for arg in "$@"; do
 
 	# skip arguments demanded by options
-	# and already shifted
+	# and already parsed
 	[[ $skip_next -gt 0 ]] && {
 		((skip_next--))
 		continue
 	}
-
-	# shift for every command, option, bunch
-	shift
 
 	# options parsing
 	# if we encount an option we will unset arg[0]
@@ -113,12 +130,14 @@ for arg in "$@"; do
 	# as single arguments where the loop is executed
 	# only once. 
 	# When an option occures demanding a second parameter
-	# always $1 is used, shifted and skip_next is increased. 
+	# always $1 is used and skip_next is increased. 
 
 	# for $arg[@] cleanup
 	idx=1
 
 	# only if $arg[0] is unset there are options to handle
+	# short options are missing the leading dash since parsing to $arg
+	# where long options kept their leading dashes
 	[[ ! ${arg[0]} ]] && {
 		for option in "${arg[@]}"; do
 				case $option in
@@ -135,7 +154,6 @@ for arg in "$@"; do
 						day=$1
 						# be grateful with missing leading zero
 						[[ ${#day} -eq 1 ]] && day=0$day
-						shift
 						((skip_next++))
 						;;
 
@@ -143,7 +161,6 @@ for arg in "$@"; do
 						month=$1
 						# be grateful with missing leading zero
 						[[ ${#month} -eq 1 ]] && month=0$month
-						shift
 						((skip_next++))
 						;;
 
@@ -151,13 +168,11 @@ for arg in "$@"; do
 						year=$1
 						# be grateful with missing leading zero
 						[[ ${#year} -eq 1 ]] && year=0$year
-						shift
 						((skip_next++))
 						;;
 
 					D|--date)
 						date=$1
-						shift
 						((skip_next++))
 						;;
 
@@ -166,8 +181,8 @@ for arg in "$@"; do
 						echo
 						;;
 
-					a|--amamedis) echo set amamedis
-						amamedis=true
+					a|--amamedis) 
+						identifier=a
 						;;
 
 					"") # ignore empty
@@ -187,6 +202,9 @@ for arg in "$@"; do
 	}
 done
 
+# now after option parsing $stripped should contain only
+# command and argument
+
 # assemble date
 # if date is set, other options -dmy are ignored.
 if [[ $date ]]; then
@@ -196,19 +214,22 @@ else
 	date=$(date -d "${year:-$(date +%y)}${month:-$(date +%m)}${day:-$(date +%d)}" +%F)
 fi
 
+# exit on error while setting date
 [[ $? -ne 0 ]] && {
 	echo error setting date
 	exit -1
 }
 
-echo amamedis is ${amamedis:-not set}
 
-# we are done parsing the options.
-# parse command
+# we are done parsing the options and setting the date.
 case ${stripped[1]} in
 
-	"") ;; # catch empty
+	# catch empty
+	"") 
+		help
+		;; 
 
+	# duration given
 	*([0-9])*(:)*([0-9]))
 		duration=${stripped[1]}
 
@@ -236,9 +257,10 @@ case ${stripped[1]} in
 
 		comment=${stripped[@]}
 
-		execute=entry
+		entry
 		;;
 
+	# from-to given
 	*([0-9])*(:)*([0-9])-*([0-9])*(:)*([0-9]))
 		fromto=${stripped[1]}
 
@@ -262,33 +284,48 @@ case ${stripped[1]} in
 		
 		unset stripped[1]
 		comment=${stripped[@]}
-		execute=entry
+
+		entry
 		;;
 
-	parse)
-		execute=parse
-		;;
-
-	report) echo report.
-		execute=report
-		;;
-	
-	*) echo command not found: ${stripped[@]}
-esac
-
-
-# command execution
-
-case $execute in
-	entry)
-		echo $date $(bc <<< "scale=2; $durations/3600")h \($durations\) $from-$to \($unix_from-$unix_to\) $comment 
-		echo e,$(date -d "$date" +%Y,%m,%d),$durations,$unix_from,$unix_to,\"$comment\" | tee -a $OUTFILE
-		;;
 	parse)
 		$PARSER $OUTFILE
 		;;
-	*)
-		echo nothing to do
+
+	report) 
+		echo not implemented yet
+		exit 1
+		;;
+
+	sync)
+		echo not implemented yet
+		exit 1
+		;;
+	
+	state)
+		echo not implemented yet
+		exit 1
+		;;
+
+	undo)
+		echo not implemented yet
+		exit 1
+		;;
+	
+	redo)
+		echo not implemented yet
+		exit 1
+		;;
+	
+	completion)
+		echo not implemented yet
+		exit 1
+		;;
+
+	
+	*) 
+		echo command not found: ${stripped[@]}
+		exit -1
 		;;
 esac
 
